# Generated by Django 3.0 on 2020-09-25 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500)),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('video', models.URLField(blank=True, db_index=True, max_length=128, unique=True)),
            ],
        ),
    ]
